# Generated by Django 4.0.3 on 2022-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reset',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reset',
            name='email',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reset',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
